---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(tidyverse)
library(magrittr)
getwd()
```

```{r}
path <-  "Safety/features/"
temp <-  list.files(path)
data_safety <- list()
for (i in 1:length(temp)){ 
  link <- paste(path,temp[i],sep = "")
  data_safety[[i]] <- fread(link) 
}
data_full <- reduce(data_safety,bind_rows)

```

```{r}
summary(data_full)
```

```{r}
glimpse(data_full)
```

```{r}
path_label <-  "Safety/labels/"
temp <-  list.files(path_label)
label <- fread(paste(path_label,temp[1],sep = ""))
`%!in%` = Negate(`%in%`)
label <- label%>%
  mutate(bookingID=as.character(bookingID))

data_full <- data_full %>%
  mutate(bookingID=as.character(bookingID))
  
duplicated_data <- label %>% 
  group_by(bookingID) %>%
  mutate(rank=row_number(bookingID)) %>%
  filter(rank>1)

data_clean <- data_full %>% 
  filter(bookingID%!in%duplicated_data$bookingID)

```

```{r}
freq_table <- data_clean %>% 
  mutate(rowId=1:nrow(data_clean)) %>% 
  filter(bookingID%!in%duplicated_data$bookingID) %>% 
  group_by(bookingID) %>% 
  summarise(n=n())

mean(freq_table$n)
```


```{r}
table(label$label)
```

```{r}
data_withLabel <- data_clean %>% 
  inner_join(label,by="bookingID")
```


```{r}
head(data_withLabel)
```

```{r}
glimpse(data_withLabel)
```

```{r}
summary(data_withLabel)
```


```{r}
summary(data_full)
```

```{r}
glimpse(data_full)
```

```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

library(moments)
feature_set1 <- data_withLabel%>% 
  mutate(
    distance = second*Speed,
    acceleration_total = sqrt((acceleration_x^2)+(acceleration_y^2)+(acceleration_z^2)),
    gyro_total = sqrt((gyro_x^2)+(gyro_y^2)+(gyro_z^2))
  ) %>% 
  group_by(bookingID) %>% 
  summarise(
    n = n(),
    Accuracy_mean = mean(Accuracy),
    Accuracy_mode = getmode(Accuracy),
    Accuracy_median = median(Accuracy),
    Accuracy_sd = var(Accuracy),
    Accuracy_min = min(Accuracy),
    Accuracy_max = max(Accuracy),
    Accuracy_skew = skewness(Accuracy),
    Accuracy_kurt = kurtosis(Accuracy),
    Bearing_mean = mean(Bearing),
    Bearing_mode = getmode(Bearing),
    Bearing_median = median(Bearing),
    Bearing_sd = var(Bearing),
    Bearing_min = min(Bearing),
    Bearing_max = max(Bearing),
    Bearing_skew = skewness(Bearing),
    Bearing_kurt = kurtosis(Bearing),
    acceleration_x_mean = mean(acceleration_x),
    acceleration_x_mode = getmode(acceleration_x),
    acceleration_x_median = median(acceleration_x),
    acceleration_x_sd = var(acceleration_x),
    acceleration_x_min = min(acceleration_x),
    acceleration_x_max = max(acceleration_x),
    acceleration_x_skew = skewness(acceleration_x),
    acceleration_x_kurt = kurtosis(acceleration_x),
    acceleration_y_mean = mean(acceleration_y),
    acceleration_y_mode = getmode(acceleration_y),
    acceleration_y_median = median(acceleration_y),
    acceleration_y_sd = var(acceleration_y),
    acceleration_y_min = min(acceleration_y),
    acceleration_y_max = max(acceleration_y),
    acceleration_y_skew = skewness(acceleration_y),
    acceleration_y_kurt = kurtosis(acceleration_y),
    acceleration_z_mean = mean(acceleration_z),
    acceleration_z_mode = getmode(acceleration_z),
    acceleration_z_median = median(acceleration_z),
    acceleration_z_sd = var(acceleration_z),
    acceleration_z_min = min(acceleration_z),
    acceleration_z_max = max(acceleration_z),
    acceleration_z_skew = skewness(acceleration_z),
    acceleration_z_kurt = kurtosis(acceleration_z),
    gyro_x_mean = mean(gyro_x),
    gyro_x_mode = getmode(gyro_x),
    gyro_x_median = median(gyro_x),
    gyro_x_sd = var(gyro_x),
    gyro_x_min = min(gyro_x),
    gyro_x_max = max(gyro_x),
    gyro_x_skew = skewness(gyro_x),
    gyro_x_kurt = kurtosis(gyro_x),
    gyro_y_mean = mean(gyro_y),
    gyro_y_mode = getmode(gyro_y),
    gyro_y_median = median(gyro_y),
    gyro_y_sd = var(gyro_y),
    gyro_y_min = min(gyro_y),
    gyro_y_max = max(gyro_y),
    gyro_y_skew = skewness(gyro_y),
    gyro_y_kurt = kurtosis(gyro_y),
    gyro_z_mean = mean(gyro_z),
    gyro_z_mode = getmode(gyro_z),
    gyro_z_median = median(gyro_z),
    gyro_z_sd = var(gyro_z),
    gyro_z_min = min(gyro_z),
    gyro_z_max = max(gyro_z),
    gyro_z_skew = skewness(gyro_z),
    gyro_z_kurt = kurtosis(gyro_z),
    Speed_mean = mean(Speed),
    Speed_mode = getmode(Speed),
    Speed_median = median(Speed),
    Speed_sd = var(Speed),
    Speed_min = min(Speed),
    Speed_max = max(Speed),
    Speed_skew = skewness(Speed),
    Speed_kurt = kurtosis(Speed),
    Speed_total = sum(Speed),
    second_mean = mean(second),
    second_mode = getmode(second),
    second_median = median(second),
    second_sd = var(second),
    second_min = min(second),
    second_max = max(second),
    second_skew = skewness(second),
    second_kurt = kurtosis(second),
    second_total = sum(second),
    distance_mean = mean(distance),
    distance_mode = getmode(distance),
    distance_median = median(distance),
    distance_sd = var(distance),
    distance_min = min(distance),
    distance_max = max(distance),
    distance_skew = skewness(distance),
    distance_kurt = kurtosis(distance),
    distance_total = sum(distance),
    acceleration_total_mean = mean(acceleration_total),
    acceleration_total_mode = getmode(acceleration_total),
    acceleration_total_median = median(acceleration_total),
    acceleration_total_sd = var(acceleration_total),
    acceleration_total_min = min(acceleration_total),
    acceleration_total_max = max(acceleration_total),
    acceleration_total_skew = skewness(acceleration_total),
    acceleration_total_kurt = kurtosis(acceleration_total),
    acceleration_total_total = sum(acceleration_total),
    gyro_total_mean = mean(gyro_total),
    gyro_total_mode = getmode(gyro_total),
    gyro_total_median = median(gyro_total),
    gyro_total_sd = var(gyro_total),
    gyro_total_min = min(gyro_total),
    gyro_total_max = max(gyro_total),
    gyro_total_skew = skewness(gyro_total),
    gyro_total_kurt = kurtosis(gyro_total),
    gyro_total_total = sum(gyro_total)
  ) %>% 
  mutate(
    acceleration_agr_mean = sqrt((acceleration_x_mean^2) + 
                                 (acceleration_y_mean^2)+
                                 (acceleration_z_mean^2)),
    acceleration_agr_mode = sqrt((acceleration_x_mode^2) + 
                                 (acceleration_y_mode^2)+
                                 (acceleration_z_mode^2)),
    acceleration_agr_median = sqrt((acceleration_x_median^2) + 
                                 (acceleration_y_median^2)+
                                 (acceleration_z_median^2)),
    acceleration_agr_min = sqrt((acceleration_x_min^2) + 
                                 (acceleration_y_min^2)+
                                 (acceleration_z_min^2)),
    acceleration_agr_max = sqrt((acceleration_x_max^2) + 
                                 (acceleration_y_max^2)+
                                 (acceleration_z_max^2)),
    gyro_agr_mean = sqrt((gyro_x_mean^2) + 
                                 (gyro_y_mean^2)+
                                 (gyro_z_mean^2)),
    gyro_agr_mode = sqrt((gyro_x_mode^2) + 
                                 (gyro_y_mode^2)+
                                 (gyro_z_mode^2)),
    gyro_agr_median = sqrt((gyro_x_median^2) + 
                                 (gyro_y_median^2)+
                                 (gyro_z_median^2)),
    gyro_agr_min = sqrt((gyro_x_min^2) + 
                                 (gyro_y_min^2)+
                                 (gyro_z_min^2)),
    gyro_agr_max = sqrt((gyro_x_max^2) + 
                                 (gyro_y_max^2)+
                                 (gyro_z_max^2)),
    distance_agr_mean = second_mean*Speed_mean,
    distance_agr_mode = second_mode*Speed_mode,
    distance_agr_median = second_median*Speed_median,
    distance_agr_min = second_min*Speed_min,
    distance_agr_max = second_max*Speed_max
  )

```

#Train_Feature Set 1
```{r}
Data_Feature_set1 <- feature_set1 %>%
  inner_join(label,by ="bookingID")  %>% 
  column_to_rownames(var = "bookingID")
  
```
#Feature Set Mean
```{r}
feature_set_mean <- Data_Feature_set1 %>% 
  select(
    n,
    contains("mean"),
    second_total,
    distance_total,
    label
  )
```

#Feature Set Median
```{r}
feature_set_median <- Data_Feature_set1 %>% 
  select(
    n,
    contains("median"),
    distance_total,
    second_total,
    label
  )
```


#Feature Set Mode
```{r}
feature_set_mode <- Data_Feature_set1 %>% 
  select(
    n,
    contains("mode"),
    distance_total,
    second_total,
    label
  )
```

#Feature Set min
```{r}
feature_set_min <- Data_Feature_set1 %>% 
  select(
    n,
    contains("min"),
    distance_total,
    second_total,
    label
  )
```

#Feature Set max
```{r}
feature_set_max <- Data_Feature_set1 %>% 
  select(
    n,
    contains("max"),
    distance_total,
    second_total,
    label
  )
```

#Feature Set sd
```{r}
feature_set_sd <- Data_Feature_set1 %>% 
  select(
    n,
    contains("sd"),
    distance_total,
    second_total,
    label
  )
```

#Feature Set meansd
```{r}
feature_set_meansd <- Data_Feature_set1 %>% 
  select(
    n,
    contains("sd"),
    contains("mean"),
    distance_total,
    second_total,
    label
  )
```

#Feature Set Kombinasi 1
```{r}
feature_set_komb1 <- Data_Feature_set1 %>% 
  select(
    n,
    Accuracy_mean,
    Bearing_mean,
    acceleration_total_mean,
    gyro_total_mean,
    acceleration_agr_mean,
    gyro_agr_mean,
    second_total,
    distance_total,
    label
  )
```

```{r}
library(xgboost)
set.seed(2019)
```
#Modeling
#Feature Set Mean


```{r}
#Data_Feature_set1$label <- as.factor(Data_Feature_set1$label)

n <- nrow(Data_Feature_set1)
i_test <- sample(1:n,size = 0.3 * n)
i_train <- (1:n)[-i_test]
Data_test <- Data_Feature_set1[i_test,]
Data_train <- Data_Feature_set1[i_train,]
```

```{r}
prop.table(table(Data_Feature_set1$label))
```

```{r}
mat_train <- as.matrix(Data_train %>% 
                    select(-bookingID,-label))
mat_test <- as.matrix(Data_test %>% 
                    select(-bookingID,-label))
dtrain <- xgb.DMatrix(data = mat_train,label = Data_train$label %>% magrittr::not()) 
dtest <- xgb.DMatrix(data = mat_test,label=Data_test$label %>% magrittr::not())
```

```{r}
params <- list(booster = "gbtree", 
               objective = "binary:logistic", 
               eta=0.3, 
               gamma=0, 
               max_depth=6, 
               min_child_weight=1, 
               subsample=1, 
               colsample_bytree=1)
feature_set_mean.matrix <- xgb.DMatrix(data = as.matrix(Data_Feature_set1 %>% 
                                         select(-label)),label = Data_Feature_set1$label) 
xgbcv <- xgb.cv( params = params, 
                 data = feature_set_mean.matrix, 
                 nrounds = 100, 
                 nfold = 5, 
                 showsd = T, 
                 stratified = T,  
                 maximize = F)

xgb1 <- xgb.train (params = params, 
                   data = feature_set_mean.matrix, 
                   nrounds = 205, 
                   watchlist = list(val=feature_set_mean.matrix,
                                    train=feature_set_mean.matrix), 
                   print.every.n = 10, 
                   early.stop.round = 10, 
                   maximize = F , 
                   eval_metric = "error")

```

```{r}
model <- xgboost(data = dtrain, # the data   
                 nround = 205, # max number of boosting iterations
                 objective = "binary:logistic") 
```

```{r}
pred <- predict(model,dtest)
err <- mean(as.numeric(pred > 0.5) != Data_test$label)
print(paste("test-error=", err))
```

```{r}
xgb.plot.multi.trees(feature_names = names(dtrain), 
                     model = model)
```

```{r}
importance_matrix <- xgb.importance(names(dtrain), model = model)

# and plot it!
xgb.plot.importance(importance_matrix)
```

```{r}
library(rpart)
library(ROCR)
Tree <- rpart(label ~ ., data = Data_train[,-1],method = "class")
FitTree <- predict(Tree,newdata = Data_test,type = "prob")[,2]
pred.tree <- prediction(FitTree,Data_test$label)
perf.tree <- performance(pred.tree, "tpr", "fpr")
library(rpart.plot)
par(mar=c(5,6,4,2)+0.1)
prp(Tree,type=4,extra=6)
```

```{r}
plot(perf.tree)
```

```{r}
AUCTree=performance(pred.tree, measure = "auc")@y.values[[1]]
cat("AUC: ",AUCTree,"n")
```

```{r}
library(randomForest)
RF <- randomForest(label ~ . ,data = Data_train[,-1])
fitRF <- predict(RF,newdata = Data_test[,-1],type = "prob")[,2]
pred.RF <- prediction(fitRF,test$Bad_label)
perf.RF <- performance(pred.RF, "tpr", "fpr")
plot(perf.RF)
```

```{r}

```

